# Generated by Django 4.2 on 2023-04-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaddress',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin'), ('BCH', 'Bitcoin Cash'), ('XRP', 'Ripple'), ('XLM', 'Stellar')], max_length=10),
        ),
    ]
