# Generated by Django 4.2 on 2023-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_api', '0002_alter_cryptoaddress_cryptocurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoaddress',
            name='encrypted_private_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
